<?php

class ProxyInfo extends AppModel
{
	var $belongsTo=array
		(
			'CompanyUserInfo'=>array('className'=>'CompanyUserInfo')
		);
	 var $validate=array
    (
       'product_name'=>array
        (
            'rule'=>array('between',1,20),
            'message'=>'产品名称长度不正确，长度1-20'
        ),
       'product_code'=>array
        (
            'rule'=>array('between',1,50),
            'message'=>'产品编号不能为空'
        ),      
        'product_area'=>array
        (
            'rule'=>array('between',1,200),
            'message'=>'代理地区最长为200'
        ),      
        'product_unit'=>array
        (
            'rule'=>array('between',1,50),
            'message'=>'产品单位不能超过50'
        ),      
        'product_introduce'=>array
        (
            'rule'=>array('between',1,500),
            'message'=>'产品介绍不能超过500'
        ),
	'product_claim'=>array
	(
	    'rule'=>array('maxLength',200),
	    'message'=>'长度不能超过200',
	     'allowEmpty'=>true
	),
	
	'product_support'=>array
	(
	    'rule'=>array('maxLength',300),
	    'message'=>'长度不能超过300',
	     'allowEmpty'=>true
	),
        'phone'=>array
        (
            'rule'=>array('custom','/((\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1}))$)/'),
             'message'=>'电话格式不正确'
        ),      
        'qq'=>array
        (
            'rule'=>array('custom','/^[0-9]{5,13}$/'),
             'message'=>'QQ格式不正确'
        ),      
        'product_type'=>array
        (
            'rule'=>'notEmpty',
             'message'=>'产品类型格式不正确'
        ),      
        'function'=>array
        (
            'rule'=>'notEmpty',
             'message'=>'功能类型格式不正确'
        ),      
        'department'=>array
        (
            'rule'=>'notEmpty',
             'message'=>'科室类型格式不正确'
        ),      
        'material'=>array
        (
            'rule'=>'notEmpty',
             'message'=>'请选择列表中一项'
        ),        
        'deadline'=>array
        (
            'rule'=>'date',
             'message'=>'到期时间格式不正确'
        )   
    );
}

?>
